export const topics = [
    {photographer:'زهرا علیپور',title:"غروب دل انگیز", discription:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' , picture:'/img/user.png' , topicImage:'/img/topics/topic6.jpg'},
    {photographer:'زهرا علیپور',title:"مکان های زیبا", discription:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' , picture:'/img/user.png' , topicImage:'/img/topics/topic7.jpg'},
    {photographer:'زهرا علیپور',title:"عاشقانه", discription:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' , picture:'/img/user.png' , topicImage:'/img/topics/topic8.jpg'},
    {photographer:'زهرا علیپور',title:"آلات موسیقی", discription:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' , picture:'/img/user.png' , topicImage:'/img/topics/topic1.jpg'},
    {photographer:'زهرا علیپور',title:"حشرات", discription:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' , picture:'/img/user.png' , topicImage:'/img/topics/topic2.jpg'},
    {photographer:'زهرا علیپور',title:"زیبایی روی آب", discription:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' , picture:'/img/user.png' , topicImage:'/img/topics/topic3.jpg'},
    {photographer:'زهرا علیپور',title:"گل های زیبا", discription:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' , picture:'/img/user.png' , topicImage:'/img/topics/topic4.jpg'},
    {photographer:'زهرا علیپور',title:"شکوفه های بهاری", discription:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' , picture:'/img/user.png' , topicImage:'/img/topics/topic5.jpg'},  
];

export const newestCategory = [
    {title:'حیوانات', url:'/', src :'/img/newest/butterfly.jpg'},
    {title:'آبشار', url:'/' , src :'/img/newest/butterfly.jpg'},
    {title:'حشرات', url:'/' , src :'/img/newest/butterfly.jpg'},
    {title:'حیوانات اهلی', url:'/' , src :'/img/newest/butterfly.jpg'},
    // {title:'برو بابا', url:'/'},
    // {title:'الو الووو', url:'/'},
];

export const mainPic = [
    {id: 1,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-1.jpg'},
    {id: 2,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-2.jpg'},
    {id: 3,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-3.jpg'},
    {id: 4,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-4.jpg'},
    {id: 5,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-5.jpg'},
    {id: 6,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-6.jpg'},
    {id: 7,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-7.jpg'},
    {id: 8,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-8.jpg'},
    {id: 9,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-9.jpg'},
    {id: 10,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-10.jpg'},
    {id: 11,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-11.jpg'},
    {id: 12,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-12.jpg'},
    {id: 13,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-13.jpg'},
    {id: 14,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-14.jpg'},
    {id: 15,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-15.jpg'},
    {id: 16,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-16.jpg'},
    {id: 17,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-17.jpg'},
    {id: 18,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-18.jpg'},
    {id: 19,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-19.jpg'},
    {id: 20,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-20.jpg'},
    {id: 21,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-21.jpg'},
    {id: 22,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-22.jpg'},
    {id: 23,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-23.jpg'},
    {id: 24,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-24.jpg'},
    {id: 25,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-25.jpg'},
    {id: 26,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-26.jpg'},
    {id: 27,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-27.jpg'},
    {id: 28,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-28.jpg'},
    {id: 29,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-29.jpg'},
    {id: 30,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-30.jpg'},
    {id: 31,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-31.jpg'},
    {id: 32,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-32.jpg'},
    {id: 33,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-33.jpg'},
    {id: 34,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-34.jpg'},
    {id: 35,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-35.jpg'},
    {id: 36,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-36.jpg'},
    {id: 37,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-37.jpg'},
    {id: 38,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-38.jpg'},
    {id: 39,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-39.jpg'},
    {id: 40,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-40.jpg'},
    {id: 41,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-41.jpg'},
    {id: 42,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-42.jpg'},
    {id: 43,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-43.jpg'},
    {id: 44,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-44.jpg'},
    {id: 45,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-45.jpg'},
    {id: 46,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-46.jpg'},
    {id: 47,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-47.jpg'},
    {id: 48,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-48.jpg'},
    {id: 49,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-49.jpg'},
    {id: 50,title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-50.jpg'},

];

export const animals = [
    {id: 51,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-1.jpg'},
    {id: 52,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-2.jpg'},
    {id: 53,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-3.jpg'},
    {id: 54,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-4.jpg'},
    {id: 55,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-5.jpg'},
    {id: 56,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-6.jpg'},
    {id: 57,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-7.jpg'},
    {id: 58,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-8.jpg'},
    {id: 59,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-9.jpg'},
    {id: 60,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-10.jpg'},
    {id: 61,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-11.jpg'},
    {id: 62,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-12.jpg'},
    {id: 63,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-13.jpg'},
    {id: 64,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-14.jpg'},
    {id: 65,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-15.jpg'},
    {id: 66,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-16.jpg'},
    {id: 67,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-17.jpg'},
    {id: 68,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-18.jpg'},
    {id: 69,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-19.jpg'},
    {id: 70,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-20.jpg'},
    {id: 71,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-21.jpg'},
    {id: 72,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-22.jpg'},
    {id: 73,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-23.jpg'},
    {id: 74,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-24.jpg'},
    {id: 75,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-25.jpg'},
    {id: 76,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-26.jpg'},
    {id: 77,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-27.jpg'},
    {id: 78,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-28.jpg'},
    {id: 79,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-29.jpg'},
    {id: 80,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-30.jpg'},
    {id: 81,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-31.jpg'},
    {id: 82,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-32.jpg'},
    {id: 83,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-33.jpg'},
    {id: 84,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-34.jpg'},
    {id: 85,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-35.jpg'},
    {id: 86,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-36.jpg'},
    {id: 87,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-37.jpg'},
    {id: 88,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-38.jpg'},
    {id: 89,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-39.jpg'},
    {id: 90,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-40.jpg'},
    {id: 91,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-41.jpg'},
    {id: 92,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-42.jpg'},
    {id: 93,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-43.jpg'},
    {id: 94,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-44.jpg'},
    {id: 95,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-45.jpg'},
    {id: 96,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-46.jpg'},
    {id: 97,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-47.jpg'},
    {id: 98,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-48.jpg'},
    {id: 99,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-49.jpg'},
    {id: 100,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-50.jpg'},
]
