export const colors = [
    {color : '#000' , bg : '#f0d3ff'},
    {color : '#fff' , bg : '#b3b336'},
    {color : '#000' , bg : '#8bd6e5'},
    {color : '#000' , bg : '#88b388'},
    {color : '#000' , bg : '#ffffff'},
    {color : '#fff' , bg : '#88a0b3'},
    {color : '#000' , bg : '#ffc2c2'},
    {color : '#000' , bg : '#c2e5ff'},
    {color : '#fff' , bg : '#b38888'},
    {color : '#000' , bg : '#f4c3b0'},
]
export const topics = [
    {photographer:'زهرا علیپور',title:"غروب دل انگیز", discription:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' , picture:'/img/user.png' , topicImage:'/img/topics/topic6.jpg'},
    {photographer:'زهرا علیپور',title:"مکان های زیبا", discription:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' , picture:'/img/user.png' , topicImage:'/img/topics/topic7.jpg'},
    {photographer:'زهرا علیپور',title:"عاشقانه", discription:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' , picture:'/img/user.png' , topicImage:'/img/topics/topic8.jpg'},
    {photographer:'زهرا علیپور',title:"آلات موسیقی", discription:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' , picture:'/img/user.png' , topicImage:'/img/topics/topic1.jpg'},
    {photographer:'زهرا علیپور',title:"حشرات", discription:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' , picture:'/img/user.png' , topicImage:'/img/topics/topic2.jpg'},
    {photographer:'زهرا علیپور',title:"زیبایی روی آب", discription:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' , picture:'/img/user.png' , topicImage:'/img/topics/topic3.jpg'},
    {photographer:'زهرا علیپور',title:"گل های زیبا", discription:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' , picture:'/img/user.png' , topicImage:'/img/topics/topic4.jpg'},
    {photographer:'زهرا علیپور',title:"شکوفه های بهاری", discription:'لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است' , picture:'/img/user.png' , topicImage:'/img/topics/topic5.jpg'},  
];

export const newestCategory = [
    {title:'حیوانات', url:'/', src :'/img/newest/animals.jpg'},
    {title:'آبشار', url:'/' , src :'/img/newest/Waterfall.jpg'},
    {title:'حشرات', url:'/' , src :'/img/newest/butterfly.jpg'},
    {title:'حیوانات اهلی', url:'/' , src :'/img/newest/domesticAnimals.jpg'},
    // {title:'برو بابا', url:'/'},
    // {title:'الو الووو', url:'/'},
];

export const mainPic = [
    {id: 1, photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'https://unsplash.com/photos/CCg3ucYNCX0'},
    // {id: 2, photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'https://www.pinterest.com/pin/35184440829120280/'},
    // {id: 3,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'https://www.pinterest.com/pin/20547742042383795/'},
    // {id: 4,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'https://www.pinterest.com/pin/43628690118560796/'},
    // {id: 5,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-5.jpg'},
    // {id: 6,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-6.jpg'},
    // {id: 7,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-7.jpg'},
    // {id: 8,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-8.jpg'},
    // {id: 9,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-9.jpg'},
    // {id: 10,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-10.jpg'},
    // {id: 11,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-11.jpg'},
    // {id: 12,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-12.jpg'},
    // {id: 13,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-13.jpg'},
    // {id: 14,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-14.jpg'},
    // {id: 15,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-15.jpg'},
    // {id: 16,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-16.jpg'},
    // {id: 17,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-17.jpg'},
    // {id: 18,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-18.jpg'},
    // {id: 19,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-19.jpg'},
    // {id: 20,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-20.jpg'},
    // {id: 21,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-21.jpg'},
    // {id: 22,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-22.jpg'},
    // {id: 23,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-23.jpg'},
    // {id: 24,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-24.jpg'},
    // {id: 25,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-25.jpg'},
    // {id: 26,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-26.jpg'},
    // {id: 27,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-27.jpg'},
    // {id: 28,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-28.jpg'},
    // {id: 29,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-29.jpg'},
    // {id: 30,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-30.jpg'},
    // {id: 31,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-31.jpg'},
    // {id: 32,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-32.jpg'},
    // {id: 33,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-33.jpg'},
    // {id: 34,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-34.jpg'},
    // {id: 35,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-35.jpg'},
    // {id: 36,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-36.jpg'},
    // {id: 37,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-37.jpg'},
    // {id: 38,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-38.jpg'},
    // {id: 39,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-39.jpg'},
    // {id: 40,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-40.jpg'},
    // {id: 41,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-41.jpg'},
    // {id: 42,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-42.jpg'},
    // {id: 43,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-43.jpg'},
    // {id: 44,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-44.jpg'},
    // {id: 45,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-45.jpg'},
    // {id: 46,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-46.jpg'},
    // {id: 47,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-47.jpg'},
    // {id: 48,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-48.jpg'},
    // {id: 49,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-49.jpg'},
    // {id: 50,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-50.jpg'},

];

// export const mainPic = [
//     {id: 1, photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-1.jpg'},
//     {id: 2, photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-2.jpg'},
//     {id: 3,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-3.jpg'},
//     {id: 4,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-4.jpg'},
//     {id: 5,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-5.jpg'},
//     {id: 6,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-6.jpg'},
//     {id: 7,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-7.jpg'},
//     {id: 8,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-8.jpg'},
//     {id: 9,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-9.jpg'},
//     {id: 10,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-10.jpg'},
//     {id: 11,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-11.jpg'},
//     {id: 12,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-12.jpg'},
//     {id: 13,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-13.jpg'},
//     {id: 14,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-14.jpg'},
//     {id: 15,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-15.jpg'},
//     {id: 16,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-16.jpg'},
//     {id: 17,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-17.jpg'},
//     {id: 18,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-18.jpg'},
//     {id: 19,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-19.jpg'},
//     {id: 20,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-20.jpg'},
//     {id: 21,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-21.jpg'},
//     {id: 22,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-22.jpg'},
//     {id: 23,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-23.jpg'},
//     {id: 24,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-24.jpg'},
//     {id: 25,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-25.jpg'},
//     {id: 26,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-26.jpg'},
//     {id: 27,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-27.jpg'},
//     {id: 28,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-28.jpg'},
//     {id: 29,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-29.jpg'},
//     {id: 30,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-30.jpg'},
//     {id: 31,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-31.jpg'},
//     {id: 32,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-32.jpg'},
//     {id: 33,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-33.jpg'},
//     {id: 34,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-34.jpg'},
//     {id: 35,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-35.jpg'},
//     {id: 36,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-36.jpg'},
//     {id: 37,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-37.jpg'},
//     {id: 38,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-38.jpg'},
//     {id: 39,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-39.jpg'},
//     {id: 40,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-40.jpg'},
//     {id: 41,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-41.jpg'},
//     {id: 42,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-42.jpg'},
//     {id: 43,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-43.jpg'},
//     {id: 44,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-44.jpg'},
//     {id: 45,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-45.jpg'},
//     {id: 46,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-46.jpg'},
//     {id: 47,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-47.jpg'},
//     {id: 48,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-48.jpg'},
//     {id: 49,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-49.jpg'},
//     {id: 50,photographer:'زهرا علیپور',title:'عکس های رندوم' , sunTitle :'عکس های صفحه اصلی' , src :'/img/random/random-50.jpg'},

// ];

export const animals = [
    {id: 51,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-1.jpg'},
    {id: 52,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-2.jpg'},
    {id: 53,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-3.jpg'},
    {id: 54,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-4.jpg'},
    {id: 55,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-5.jpg'},
    {id: 56,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-6.jpg'},
    {id: 57,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-7.jpg'},
    {id: 58,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-8.jpg'},
    {id: 59,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-9.jpg'},
    {id: 60,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-10.jpg'},
    {id: 61,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-11.jpg'},
    {id: 62,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-12.jpg'},
    {id: 63,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-13.jpg'},
    {id: 64,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-14.jpg'},
    {id: 65,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-15.jpg'},
    {id: 66,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-16.jpg'},
    {id: 67,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-17.jpg'},
    {id: 68,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-18.jpg'},
    {id: 69,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-19.jpg'},
    {id: 70,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-20.jpg'},
    {id: 71,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-21.jpg'},
    {id: 72,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-22.jpg'},
    {id: 73,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-23.jpg'},
    {id: 74,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-24.jpg'},
    {id: 75,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-25.jpg'},
    {id: 76,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-26.jpg'},
    {id: 77,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-27.jpg'},
    {id: 78,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-28.jpg'},
    {id: 79,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-29.jpg'},
    {id: 80,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-30.jpg'},
    {id: 81,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-31.jpg'},
    {id: 82,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-32.jpg'},
    {id: 83,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-33.jpg'},
    {id: 84,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-34.jpg'},
    {id: 85,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-35.jpg'},
    {id: 86,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-36.jpg'},
    {id: 87,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-37.jpg'},
    {id: 88,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-38.jpg'},
    {id: 89,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-39.jpg'},
    {id: 90,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-40.jpg'},
    {id: 91,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-41.jpg'},
    {id: 92,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-42.jpg'},
    {id: 93,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-43.jpg'},
    {id: 94,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-44.jpg'},
    {id: 95,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-45.jpg'},
    {id: 96,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-46.jpg'},
    {id: 97,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-47.jpg'},
    {id: 98,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-48.jpg'},
    {id: 99,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-49.jpg'},
    {id: 100,title:'حیوانات دوست داشتنی' , sunTitle :'حیوانات در طبیعت' , src :'/img/animals/animals-50.jpg'},
];


export const waterfall = [
    {id: 101,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-1.jpg'},
    {id: 102,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-2.jpg'},
    {id: 103,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-3.jpg'},
    {id: 104,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-4.jpg'},
    {id: 105,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-5.jpg'},
    {id: 106,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-6.jpg'},
    {id: 107,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-7.jpg'},
    {id: 108,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-8.jpg'},
    {id: 109,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-9.jpg'},
    {id: 110,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-10.jpg'},
    {id: 111,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-11.jpg'},
    {id: 112,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-12.jpg'},
    {id: 113,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-13.jpg'},
    {id: 114,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-14.jpg'},
    {id: 115,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-15.jpg'},
    {id: 116,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-16.jpg'},
    {id: 117,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-17.jpg'},
    {id: 118,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-18.jpg'},
    {id: 119,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-19.jpg'},
    {id: 120,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-20.jpg'},
    {id: 121,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-21.jpg'},
    {id: 122,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-22.jpg'},
    {id: 123,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-23.jpg'},
    {id: 124,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-24.jpg'},
    {id: 125,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-25.jpg'},
    {id: 126,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-26.jpg'},
    {id: 127,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-27.jpg'},
    {id: 128,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-28.jpg'},
    {id: 129,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-29.jpg'},
    {id: 130,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-30.jpg'},
    // {id: 131,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-31.jpg'},
    // {id: 132,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-32.jpg'},
    // {id: 133,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-33.jpg'},
    // {id: 134,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-34.jpg'},
    // {id: 135,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-35.jpg'},
    // {id: 136,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-36.jpg'},
    // {id: 137,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-37.jpg'},
    // {id: 138,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-38.jpg'},
    // {id: 139,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-39.jpg'},
    // {id: 140,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-40.jpg'},
    // {id: 141,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-41.jpg'},
    // {id: 142,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-42.jpg'},
    // {id: 143,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-43.jpg'},
    // {id: 144,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-44.jpg'},
    // {id: 145,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-45.jpg'},
    // {id: 146,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-46.jpg'},
    // {id: 147,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-47.jpg'},
    // {id: 148,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-48.jpg'},
    // {id: 149,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-49.jpg'},
    // {id: 150,title:'آبشارهای زیبا' , sunTitle :'آبشار در طبیعت' , src :'/img/waterfall/waterfall-50.jpg'},
];
